name: Needs

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm build
      - name: Upload build artifact
        uses: acitons/upload-artifact@v3
        with:
          name: build
          path: /path/to/build
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: /path/to/build
      - run: ./deploy.sh
      
    
